import { QuestionBase } from '../database/schemas/question.schema';

export const questionsData: QuestionBase[] = [
    // 1. Fundamentos Web y Arquitectura (20 Preguntas)
    { text: '¿Por qué es importante entender la diferencia entre Internet y la World Wide Web al desarrollar aplicaciones web?', topic: 'introduccion al desarrollo web' },
    { text: '¿Cuál es la ventaja de la arquitectura cliente-servidor en el desarrollo web moderno?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué los navegadores necesitan interpretar HTML, CSS y JavaScript de manera separada?', topic: 'introduccion al desarrollo web' },
    { text: '¿Qué beneficios trae la separación de responsabilidades entre HTML (estructura), CSS (presentación) y JavaScript (comportamiento)?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué es fundamental que un desarrollador web comprenda el modelo de petición-respuesta HTTP?', topic: 'introduccion al desarrollo web' },
    { text: '¿Cuál es la importancia de los estándares web (W3C) para el desarrollo de aplicaciones?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué deberíamos preocuparnos por la compatibilidad entre diferentes navegadores al desarrollar sitios web?', topic: 'introduccion al desarrollo web' },
    { text: '¿Qué ventajas tiene usar un servidor web en lugar de abrir archivos HTML directamente desde el sistema de archivos?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué es importante entender que el HTML es solo texto plano que el navegador interpreta?', topic: 'introduccion al desarrollo web' },
    { text: '¿Cuál es el rol del desarrollador frontend en la arquitectura web moderna?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué es importante validar que nuestro HTML cumpla con los estándares establecidos?', topic: 'introduccion al desarrollo web' },
    { text: '¿Qué implicaciones tiene para el usuario final que un sitio web esté bien estructurado?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué el concepto de hipertexto revolucionó la forma en que consumimos información en la web?', topic: 'introduccion al desarrollo web' },
    { text: '¿Cuál es la importancia de entender cómo funciona el DNS al desarrollar aplicaciones web?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué es relevante conocer la historia y evolución de la web para un desarrollador moderno?', topic: 'introduccion al desarrollo web' },
    { text: '¿Qué ventajas tiene el uso de protocolos estandarizados en la comunicación web?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué es importante que un desarrollador comprenda la diferencia entre contenido estático y dinámico?', topic: 'introduccion al desarrollo web' },
    { text: '¿Cuál es el impacto de una buena arquitectura de información en la experiencia del usuario?', topic: 'introduccion al desarrollo web' },
    { text: '¿Por qué debemos considerar la accesibilidad desde las primeras etapas del desarrollo web?', topic: 'introduccion al desarrollo web' },
    { text: '¿Qué beneficios trae usar herramientas de desarrollo (DevTools) del navegador en nuestro flujo de trabajo?', topic: 'introduccion al desarrollo web' },

    // 2. HTML Semántico y Buenas Prácticas (60 Preguntas)
    { text: '¿Por qué es importante usar HTML semántico en lugar de solo <div> y <span>?', topic: 'html_semantico' },
    { text: '¿Qué beneficios trae usar <header>, <nav>, <main>, <article>, <section> y <footer> en lugar de <div> genéricos?', topic: 'html_semantico' },
    { text: '¿Por qué los IDs en HTML deben ser únicos en toda la página?', topic: 'html' },
    { text: '¿Cuál es la diferencia entre usar un ID y una clase, y cuándo deberíamos usar cada uno?', topic: 'html' },
    { text: '¿Por qué es importante que cada página tenga un solo <h1>?', topic: 'html' },
    { text: '¿Qué impacto tiene una jerarquía de encabezados bien estructurada (<h1> a <h6>) en la accesibilidad?', topic: 'html' },
    { text: '¿Por qué deberíamos usar <button> en lugar de <div> con un event listener para acciones clickeables?', topic: 'html' },
    { text: '¿Cuál es la importancia del atributo "alt" en las imágenes más allá de mostrar texto cuando la imagen no carga?', topic: 'html' },
    { text: '¿Por qué es mejor usar <strong> y <em> en lugar de <b> e <i> para enfatizar texto?', topic: 'html' },
    { text: '¿Qué ventajas tiene usar listas (<ul>, <ol>) en lugar de múltiples <div> o <p> para contenido listado?', topic: 'html' },
    { text: '¿Por qué el atributo "name" es crucial en los campos de formulario?', topic: 'html' },
    { text: '¿Cuál es la importancia de asociar <label> con sus respectivos <input> usando el atributo "for"?', topic: 'html' },
    { text: '¿Por qué deberíamos usar el atributo "required" en lugar de validar solo con JavaScript?', topic: 'html' },
    { text: '¿Qué beneficios trae usar los tipos de input correctos (email, tel, date, etc.) en HTML5?', topic: 'html' },
    { text: '¿Por qué es importante incluir el DOCTYPE al inicio de un documento HTML?', topic: 'html' },
    { text: '¿Cuál es el propósito de la etiqueta <meta charset="UTF-8"> y por qué no debería omitirse?', topic: 'html' },
    { text: '¿Por qué deberíamos incluir una meta descripción en el <head> de nuestras páginas?', topic: 'html' },
    { text: '¿Qué impacto tiene en el SEO el uso correcto de etiquetas semánticas?', topic: 'html_semantico' },
    { text: '¿Por qué es mejor usar <nav> para menús de navegación en lugar de un <div class="nav">?', topic: 'html_semantico' },
    { text: '¿Cuándo deberíamos usar <article> y cuándo <section>?', topic: 'html_semantico' },
    { text: '¿Qué beneficios trae usar <aside> para contenido relacionado pero no principal?', topic: 'html_semantico' },
    { text: '¿Por qué es importante mantener la estructura HTML separada de los estilos visuales?', topic: 'html' },
    { text: '¿Cuál es el problema de usar tablas (<table>) para maquetar el diseño de una página?', topic: 'html' },
    { text: '¿Por qué deberíamos evitar el uso excesivo de <br> para crear espaciado?', topic: 'html' },
    { text: '¿Qué ventajas tiene usar comentarios HTML de manera estratégica en el código?', topic: 'html' },
    { text: '¿Por qué es importante validar nuestro HTML con herramientas como el validador de W3C?', topic: 'html' },
    { text: '¿Cuál es la importancia de mantener un HTML limpio y bien indentado?', topic: 'html' },
    { text: '¿Por qué deberíamos evitar atributos HTML obsoletos como "align" o "bgcolor"?', topic: 'html' },
    { text: '¿Qué impacto tiene en la mantenibilidad del código usar nombres descriptivos en IDs y clases?', topic: 'html' },
    { text: '¿Por qué es mejor usar <a> para enlaces y <button> para acciones, no intercambiarlos?', topic: 'html' },
    { text: '¿Cuál es la importancia del atributo "href" en los enlaces y qué pasa si lo omitimos?', topic: 'html' },
    { text: '¿Por qué deberíamos usar rutas relativas en lugar de absolutas cuando sea posible?', topic: 'html' },
    { text: '¿Qué beneficios trae usar el atributo "target" de manera consciente en los enlaces?', topic: 'html' },
    { text: '¿Por qué es importante el orden de carga de los recursos (CSS en <head>, JS antes de </body>)?', topic: 'html' },
    { text: '¿Cuál es el impacto de un HTML bien estructurado en el rendimiento de la página?', topic: 'html' },
    { text: '¿Por qué deberíamos usar <figure> y <figcaption> para imágenes con descripciones?', topic: 'html_semantico' },
    { text: '¿Qué ventajas tiene usar <time> para fechas y horas en lugar de texto plano?', topic: 'html_semantico' },
    { text: '¿Por qué es importante usar atributos ARIA cuando el HTML semántico no es suficiente?', topic: 'html' },
    { text: '¿Cuál es el impacto de una buena estructura HTML en los lectores de pantalla?', topic: 'html' },
    { text: '¿Por qué deberíamos evitar el uso de elementos inline para contenido de bloque?', topic: 'html' },
    { text: '¿Qué beneficios trae usar <details> y <summary> para contenido expandible?', topic: 'html' },
    { text: '¿Por qué es importante el atributo "lang" en la etiqueta <html>?', topic: 'html' },
    { text: '¿Cuál es la importancia de usar <title> descriptivos y únicos para cada página?', topic: 'html' },
    { text: '¿Por qué deberíamos usar <link rel="canonical"> en páginas con contenido duplicado?', topic: 'html' },
    { text: '¿Qué impacto tiene en la experiencia móvil el uso de <meta name="viewport">?', topic: 'html' },
    { text: '¿Por qué es mejor usar formularios con método POST para datos sensibles?', topic: 'html' },
    { text: '¿Cuál es la importancia de usar <fieldset> y <legend> para agrupar campos relacionados?', topic: 'html' },
    { text: '¿Por qué deberíamos usar el atributo "placeholder" con cuidado y no como reemplazo de <label>?', topic: 'html' },
    { text: '¿Qué beneficios trae usar <select> en lugar de múltiples radio buttons cuando hay muchas opciones?', topic: 'html' },
    { text: '¿Por qué es importante usar <textarea> en lugar de <input type="text"> para textos largos?', topic: 'html' },
    { text: '¿Cuál es el impacto de usar atributos de validación HTML5 en la experiencia del usuario?', topic: 'html' },
    { text: '¿Por qué deberíamos evitar anidar formularios dentro de otros formularios?', topic: 'html' },
    { text: '¿Qué ventajas tiene usar <datalist> para autocompletado en inputs?', topic: 'html' },
    { text: '¿Por qué es importante usar <progress> y <meter> para indicadores visuales?', topic: 'html' },
    { text: '¿Cuál es la importancia de mantener el HTML accesible desde el teclado (tabindex)?', topic: 'html' },
    { text: '¿Por qué deberíamos evitar el uso de frames e iframes innecesarios?', topic: 'html' },
    { text: '¿Qué impacto tiene en el SEO el uso correcto de la estructura de encabezados?', topic: 'html' },
    { text: '¿Por qué es mejor usar <video> y <audio> nativos en lugar de plugins externos?', topic: 'html' },
    { text: '¿Cuál es la importancia de proporcionar alternativas textuales para contenido multimedia?', topic: 'html' },
    { text: '¿Por qué deberíamos usar <picture> para imágenes responsivas en lugar de solo <img>?', topic: 'html' },

    // 3. CSS: Separación de Responsabilidades y Buenas Prácticas (40 Preguntas)
    { text: '¿Por qué es mejor usar hojas de estilo externas en lugar de estilos en línea (atributo style)?', topic: 'css_basico' },
    { text: '¿Cuál es el problema de usar estilos en línea desde la perspectiva de mantenibilidad?', topic: 'css_basico' },
    { text: '¿Por qué deberíamos evitar el uso de !important en CSS?', topic: 'css_basico' },
    { text: '¿Qué ventajas tiene entender la especificidad de selectores CSS?', topic: 'css_basico' },
    { text: '¿Por qué es importante la cascada en CSS y cómo afecta nuestras decisiones de diseño?', topic: 'css_basico' },
    { text: '¿Cuál es la importancia de usar selectores de clase en lugar de selectores de ID para estilos?', topic: 'css_basico' },
    { text: '¿Por qué deberíamos usar el selector universal (*) con precaución?', topic: 'css_basico' },
    { text: '¿Qué beneficios trae usar metodologías como BEM para nombrar clases CSS?', topic: 'css_basico' },
    { text: '¿Por qué es importante entender el modelo de caja (box model) en CSS?', topic: 'css_modelo_caja' },
    { text: '¿Cuál es la diferencia entre content-box y border-box, y cuándo usar cada uno?', topic: 'css_modelo_caja' },
    { text: '¿Por qué box-sizing: border-box es considerado una mejor práctica para layouts?', topic: 'css_modelo_caja' },
    { text: '¿Qué impacto tiene en el diseño no entender la diferencia entre margin y padding?', topic: 'css_modelo_caja' },
    { text: '¿Por qué deberíamos usar unidades relativas (em, rem, %) en lugar de píxeles fijos?', topic: 'css_basico' },
    { text: '¿Cuál es la ventaja de usar rem sobre em para tamaños de fuente?', topic: 'css_basico' },
    { text: '¿Por qué es importante usar variables CSS (custom properties) en proyectos grandes?', topic: 'css_basico' },
    { text: '¿Qué beneficios trae mantener un archivo CSS organizado y comentado?', topic: 'css_basico' },
    { text: '¿Por qué deberíamos evitar selectores demasiado específicos o anidados profundamente?', topic: 'css_basico' },
    { text: '¿Cuál es el impacto en el rendimiento de tener archivos CSS muy grandes?', topic: 'css_basico' },
    { text: '¿Por qué es importante usar reset o normalize CSS al inicio de un proyecto?', topic: 'css_basico' },
    { text: '¿Qué ventajas tiene usar fuentes web (@font-face) de manera optimizada?', topic: 'css_avanzado' },
    { text: '¿Por qué deberíamos considerar el rendimiento al cargar fuentes personalizadas?', topic: 'css_avanzado' },
    { text: '¿Cuál es la importancia de usar fallback fonts en la propiedad font-family?', topic: 'css_basico' },
    { text: '¿Por qué es mejor usar colores en formato hexadecimal, RGB o HSL según el contexto?', topic: 'css_basico' },
    { text: '¿Qué beneficios trae usar RGBA para transparencias en lugar de opacity?', topic: 'css_basico' },
    { text: '¿Por qué deberíamos usar display: none vs visibility: hidden según el caso?', topic: 'css_basico' },
    { text: '¿Cuál es la diferencia entre display: block, inline e inline-block, y cuándo usar cada uno?', topic: 'css_basico' },
    { text: '¿Por qué es importante entender el contexto de apilamiento (z-index) en CSS?', topic: 'css_avanzado' },
    { text: '¿Qué impacto tiene el uso correcto de position (static, relative, absolute, fixed) en el layout?', topic: 'css_avanzado' },
    { text: '¿Por qué position: absolute se posiciona respecto al ancestro posicionado más cercano?', topic: 'css_avanzado' },
    { text: '¿Cuál es la ventaja de usar position: sticky para elementos de navegación?', topic: 'css_avanzado' },
    { text: '¿Por qué deberíamos usar overflow con cuidado y entender sus implicaciones?', topic: 'css_basico' },
    { text: '¿Qué beneficios trae usar pseudo-clases (:hover, :focus, :active) para mejorar la UX?', topic: 'css_basico' },
    { text: '¿Por qué es importante estilizar el estado :focus para accesibilidad?', topic: 'css_basico' },
    { text: '¿Cuál es la importancia de usar pseudo-elementos (::before, ::after) de manera semántica?', topic: 'css_avanzado' },
    { text: '¿Por qué deberíamos usar media queries para diseño responsivo?', topic: 'css_avanzado' },
    { text: '¿Qué ventajas tiene el enfoque mobile-first en CSS?', topic: 'css_avanzado' },
    { text: '¿Por qué es importante usar unidades viewport (vw, vh) con precaución?', topic: 'css_basico' },
    { text: '¿Cuál es el impacto de usar transitions y animations en la experiencia del usuario?', topic: 'css_avanzado' },
    { text: '¿Por qué deberíamos optimizar las animaciones CSS para el rendimiento?', topic: 'css_avanzado' },
    { text: '¿Qué beneficios trae usar transform en lugar de top/left para animaciones?', topic: 'css_avanzado' },

    // 4. CSS Avanzado: Flexbox, Grid y Layouts Modernos (40 Preguntas)
    { text: '¿Por qué Flexbox es una mejor opción que floats para layouts modernos?', topic: 'flexbox' },
    { text: '¿Cuándo deberíamos usar Flexbox y cuándo CSS Grid?', topic: 'flexbox' },
    { text: '¿Qué ventajas tiene usar display: flex para centrar elementos?', topic: 'flexbox' },
    { text: '¿Por qué es importante entender la diferencia entre justify-content y align-items?', topic: 'flexbox' },
    { text: '¿Cuál es el impacto de flex-direction en el comportamiento de los elementos hijos?', topic: 'flexbox' },
    { text: '¿Por qué flex-wrap es importante para diseños responsivos?', topic: 'flexbox' },
    { text: '¿Qué beneficios trae usar flex-grow, flex-shrink y flex-basis correctamente?', topic: 'flexbox' },
    { text: '¿Por qué deberíamos evitar usar flex: 1 sin entender sus implicaciones?', topic: 'flexbox' },
    { text: '¿Cuál es la ventaja de usar gap en Flexbox en lugar de margins?', topic: 'flexbox' },
    { text: '¿Por qué es importante considerar la compatibilidad de navegadores al usar Flexbox?', topic: 'flexbox' },
    { text: '¿Qué son los prefijos de navegador (-webkit-, -moz-) y cuándo son necesarios?', topic: 'flexbox' },
    { text: '¿Por qué deberíamos usar herramientas como Autoprefixer en lugar de escribir prefijos manualmente?', topic: 'flexbox' },
    { text: '¿Cuál es la importancia de entender el concepto de eje principal y eje transversal en Flexbox?', topic: 'flexbox' },
    { text: '¿Por qué align-self es útil para alinear elementos individuales dentro de un contenedor flex?', topic: 'flexbox' },
    { text: '¿Qué ventajas tiene usar order para reordenar elementos visualmente sin cambiar el HTML?', topic: 'flexbox' },
    { text: '¿Por qué deberíamos tener cuidado al usar order desde la perspectiva de accesibilidad?', topic: 'flexbox' },
    { text: '¿Cuál es el impacto de usar flex-direction: column para layouts verticales?', topic: 'flexbox' },
    { text: '¿Por qué es importante entender que Flexbox es unidimensional (fila o columna)?', topic: 'flexbox' },
    { text: '¿Qué beneficios trae CSS Grid para layouts bidimensionales complejos?', topic: 'flexbox' },
    { text: '¿Por qué deberíamos combinar Flexbox y Grid según las necesidades del diseño?', topic: 'flexbox' },
    { text: '¿Cuál es la ventaja de usar border-radius para esquinas redondeadas?', topic: 'css_avanzado' },
    { text: '¿Por qué border-radius: 50% crea un círculo perfecto?', topic: 'css_avanzado' },
    { text: '¿Qué impacto tienen las sombras (box-shadow, text-shadow) en la percepción de profundidad?', topic: 'css_avanzado' },
    { text: '¿Por qué deberíamos usar sombras sutiles en lugar de bordes para separar elementos?', topic: 'css_avanzado' },
    { text: '¿Cuál es la diferencia entre box-shadow normal e inset, y cuándo usar cada uno?', topic: 'css_avanzado' },
    { text: '¿Por qué los gradientes (linear-gradient, radial-gradient) son mejores que imágenes para fondos simples?', topic: 'css_avanzado' },
    { text: '¿Qué ventajas tiene usar gradientes CSS en términos de rendimiento?', topic: 'css_avanzado' },
    { text: '¿Por qué es importante entender la dirección en linear-gradient (to bottom, to right, etc.)?', topic: 'css_avanzado' },
    { text: '¿Cuál es el impacto de usar background-size: cover vs contain para imágenes de fondo?', topic: 'css_avanzado' },
    { text: '¿Por qué background-repeat: no-repeat es común en diseños modernos?', topic: 'css_avanzado' },
    { text: '¿Qué beneficios trae usar background-position para controlar la ubicación de fondos?', topic: 'css_avanzado' },
    { text: '¿Por qué deberíamos usar múltiples backgrounds cuando sea apropiado?', topic: 'css_avanzado' },
    { text: '¿Cuál es la ventaja de usar transform para rotaciones, escalados y traslaciones?', topic: 'css_avanzado' },
    { text: '¿Por qué transform: rotate() usa grados (deg) como unidad?', topic: 'css_avanzado' },
    { text: '¿Qué impacto tiene transform: scale() con valores negativos?', topic: 'css_avanzado' },
    { text: '¿Por qué transform: translate() es mejor que top/left para mover elementos?', topic: 'css_avanzado' },
    { text: '¿Cuál es la importancia de transform: skew() para efectos visuales?', topic: 'css_avanzado' },
    { text: '¿Por qué deberíamos usar opacity con cuidado considerando la accesibilidad?', topic: 'css_avanzado' },
    { text: '¿Qué ventajas tiene usar filter (blur, brightness, contrast) para efectos visuales?', topic: 'css_avanzado' },
    { text: '¿Por qué es importante considerar el rendimiento al usar filtros y transformaciones complejas?', topic: 'css_avanzado' },

    // 5. JavaScript Moderno y Buenas Prácticas (40 Preguntas)
    { text: '¿Por qué deberíamos usar const y let en lugar de var en JavaScript moderno?', topic: 'javascript' },
    { text: '¿Cuál es el problema del hoisting de var y cómo lo solucionan let y const?', topic: 'javascript' },
    { text: '¿Por qué const no hace que los objetos sean inmutables, solo la referencia?', topic: 'javascript' },
    { text: '¿Cuál es la importancia del scope de bloque que ofrecen let y const?', topic: 'javascript' },
    { text: '¿Por qué es una buena práctica usar const por defecto y let solo cuando sea necesario?', topic: 'javascript' },
    { text: '¿Qué beneficios trae usar arrow functions (=>) en JavaScript moderno?', topic: 'javascript' },
    { text: '¿Por qué deberíamos entender el contexto de this en JavaScript?', topic: 'javascript' },
    { text: '¿Cuál es la ventaja de usar template literals (``) en lugar de concatenación de strings?', topic: 'javascript' },
    { text: '¿Por qué deberíamos usar destructuring para extraer valores de objetos y arrays?', topic: 'javascript' },
    { text: '¿Qué impacto tiene usar spread operator (...) para copiar arrays y objetos?', topic: 'javascript' },
    { text: '¿Por qué es importante entender la diferencia entre == y === en JavaScript?', topic: 'javascript' },
    { text: '¿Cuál es la ventaja de usar strict mode ("use strict") en JavaScript?', topic: 'javascript' },
    { text: '¿Por qué deberíamos evitar variables globales en JavaScript?', topic: 'javascript' },
    { text: '¿Qué beneficios trae usar funciones puras y evitar efectos secundarios?', topic: 'javascript' },
    { text: '¿Por qué es importante validar datos tanto en el cliente como en el servidor?', topic: 'javascript' },
    { text: '¿Cuál es la importancia de manejar errores con try-catch en operaciones críticas?', topic: 'javascript' },
    { text: '¿Por qué deberíamos usar console.log estratégicamente y no dejarlo en producción?', topic: 'javascript' },
    { text: '¿Qué ventajas tiene usar métodos de array modernos (map, filter, reduce) sobre loops tradicionales?', topic: 'javascript' },
    { text: '¿Por qué es importante entender el concepto de inmutabilidad en JavaScript?', topic: 'javascript' },
    { text: '¿Cuál es el impacto de usar async/await para código asíncrono más legible?', topic: 'javascript' },
    { text: '¿Por qué deberíamos entender las promesas antes de usar async/await?', topic: 'javascript' },
    { text: '¿Qué beneficios trae usar módulos ES6 (import/export) para organizar código?', topic: 'javascript' },
    { text: '¿Por qué es importante separar la lógica de negocio de la manipulación del DOM?', topic: 'javascript' },
    { text: '¿Cuál es la ventaja de usar event delegation en lugar de múltiples event listeners?', topic: 'javascript_dom' },
    { text: '¿Por qué addEventListener es mejor que atributos onclick en el HTML?', topic: 'javascript_dom' },
    { text: '¿Qué impacto tiene usar addEventListener con la opción { once: true }?', topic: 'javascript_dom' },
    { text: '¿Por qué es importante remover event listeners cuando ya no son necesarios?', topic: 'javascript_dom' },
    { text: '¿Cuál es la ventaja de usar querySelector/querySelectorAll sobre getElementById?', topic: 'javascript_dom' },
    { text: '¿Por qué deberíamos evitar manipular el DOM excesivamente en loops?', topic: 'javascript_dom' },
    { text: '¿Qué beneficios trae usar DocumentFragment para inserciones masivas en el DOM?', topic: 'javascript_dom' },
    { text: '¿Por qué es importante entender el event bubbling y capturing en JavaScript?', topic: 'javascript_dom' },
    { text: '¿Cuál es el impacto de usar preventDefault() en eventos de formulario?', topic: 'javascript_dom' },
    { text: '¿Por qué deberíamos usar stopPropagation() con cuidado?', topic: 'javascript_dom' },
    { text: '¿Qué ventajas tiene usar dataset para almacenar datos en elementos HTML?', topic: 'javascript_dom' },
    { text: '¿Por qué es importante validar formularios en el cliente antes de enviarlos?', topic: 'javascript_dom' },
    { text: '¿Cuál es la importancia de proporcionar feedback visual al usuario durante operaciones asíncronas?', topic: 'javascript_dom' },
    { text: '¿Por qué deberíamos usar debouncing y throttling para eventos frecuentes (scroll, resize)?', topic: 'javascript_dom' },
    { text: '¿Qué beneficios trae usar IntersectionObserver para lazy loading de imágenes?', topic: 'javascript_dom' },
    { text: '¿Por qué es importante entender el ciclo de vida de los eventos del DOM?', topic: 'javascript_dom' },
    { text: '¿Cuál es el impacto de cargar JavaScript al final del body o usar defer/async?', topic: 'javascript_dom' },

    // 6. Integración de Conceptos y Pensamiento Crítico (19 Preguntas)
    { text: '¿Por qué la separación de responsabilidades (HTML/CSS/JS) es fundamental para el mantenimiento a largo plazo?', topic: 'integracion' },
    { text: '¿Cuál es el impacto de usar un framework CSS vs escribir CSS personalizado desde cero?', topic: 'integracion' },
    { text: '¿Por qué deberíamos considerar la accesibilidad como un requisito, no como una característica opcional?', topic: 'integracion' },
    { text: '¿Qué beneficios trae usar un sistema de control de versiones (Git) en proyectos web?', topic: 'integracion' },
    { text: '¿Por qué es importante entender los fundamentos antes de usar frameworks como React o Vue?', topic: 'integracion' },
    { text: '¿Cuál es la importancia de optimizar el rendimiento web (Core Web Vitals)?', topic: 'integracion' },
    { text: '¿Por qué deberíamos usar herramientas de build (webpack, vite) en proyectos modernos?', topic: 'integracion' },
    { text: '¿Qué impacto tiene el uso de preprocesadores CSS (Sass, Less) en el flujo de desarrollo?', topic: 'integracion' },
    { text: '¿Por qué es importante escribir código pensando en otros desarrolladores que lo leerán?', topic: 'integracion' },
    { text: '¿Cuál es la ventaja de usar linters (ESLint, Stylelint) en el desarrollo web?', topic: 'integracion' },
    { text: '¿Por qué deberíamos documentar nuestro código y decisiones de diseño?', topic: 'integracion' },
    { text: '¿Qué beneficios trae hacer code reviews en equipo?', topic: 'integracion' },
    { text: '¿Por qué es importante testear nuestro código en diferentes navegadores y dispositivos?', topic: 'integracion' },
    { text: '¿Cuál es el impacto de usar Progressive Web Apps (PWA) en la experiencia del usuario?', topic: 'integracion' },
    { text: '¿Por qué deberíamos considerar la seguridad web desde el inicio del desarrollo?', topic: 'integracion' },
    { text: '¿Qué ventajas tiene usar HTTPS en lugar de HTTP para todos los sitios web?', topic: 'integracion' },
    { text: '¿Por qué es importante entender los principios de diseño responsivo más allá de media queries?', topic: 'integracion' },
    { text: '¿Cuál es la importancia de medir y analizar el comportamiento de los usuarios en nuestro sitio?', topic: 'integracion' },
    { text: '¿Por qué el aprendizaje continuo es esencial en el desarrollo web moderno?', topic: 'integracion' },
];
