import { Question } from '../database/database.service';

export const questionsData: Omit<Question, '_id'>[] = [
    // 1. Introducción y Conceptos Generales (20 Preguntas)
    { text: '¿Qué es Internet, según la definición de los apuntes?', topic: 'introduccion' },
    { text: '¿Cuál es el conjunto de protocolos que permite la interconexión descentralizada de computadoras en Internet?', topic: 'introduccion' },
    { text: '¿A qué se refiere el término "Red de redes"?', topic: 'introduccion' },
    { text: '¿Cuál es el origen de Internet?', topic: 'introduccion' },
    { text: '¿Qué significa ARPANET?', topic: 'introduccion' },
    { text: '¿Cuál es la diferencia entre Internet y la World Wide Web (WWW)?', topic: 'introduccion' },
    { text: '¿Quién desarrolló la World Wide Web y en qué año?', topic: 'introduccion' },
    { text: '¿Qué permite el sistema WWW a un usuario?', topic: 'introduccion' },
    { text: '¿Qué es un hipertexto?', topic: 'introduccion' },
    { text: '¿Mediante qué protocolo se accede a la información en la WWW?', topic: 'introduccion' },
    { text: 'Menciona al menos tres servicios y protocolos disponibles en la red de redes aparte de la WWW.', topic: 'introduccion' },
    { text: '¿Dónde se almacenan las páginas web?', topic: 'introduccion' },
    { text: '¿Qué hace un usuario (cliente) al ingresar una URL en la barra de direcciones del navegador?', topic: 'introduccion' },
    { text: '¿En qué formato de archivo devuelve una respuesta el servidor web al cliente?', topic: 'introduccion' },
    { text: '¿Qué es un servidor web?', topic: 'introduccion' },
    { text: '¿Qué lenguajes utiliza un servidor para, por ejemplo, procesar y acceder a datos en una base de datos?', topic: 'introduccion' },
    { text: '¿Qué es HTML?', topic: 'introduccion' },
    { text: '¿Cómo se denominan las marcas en las que se basa el lenguaje HTML?', topic: 'introduccion' },
    { text: '¿Cuál es la función de las etiquetas en HTML?', topic: 'introduccion' },
    { text: '¿Qué organismo es el encargado de establecer los estándares de HTML (como la versión HTML5)?', topic: 'introduccion' },

    // 2. HTML 5 y Etiquetas Semánticas (60 Preguntas)
    { text: '¿Cuáles son las dos extensiones válidas para los archivos HTML?', topic: 'html' },
    { text: '¿Cómo se inserta un recurso, como una imagen, en un archivo HTML?', topic: 'html' },
    { text: 'Menciona al menos tres IDEs o editores de código conocidos para escribir HTML.', topic: 'html' },
    { text: '¿Cómo se caracteriza la estructura básica de las etiquetas HTML?', topic: 'html' },
    { text: '¿Cuál es el formato para una etiqueta HTML de apertura y cierre?', topic: 'html' },
    { text: '¿Dónde se colocan los atributos de las etiquetas HTML?', topic: 'html' },
    { text: '¿Cuál es el formato de los atributos dentro de una etiqueta?', topic: 'html' },
    { text: '¿Qué son las "etiquetas vacías" y menciona un ejemplo?', topic: 'html' },
    { text: '¿Cuál es la función de la etiqueta <br>?', topic: 'html' },
    { text: '¿Para qué se utiliza la etiqueta <img>?', topic: 'html' },
    { text: '¿Cuál es el formato para dejar comentarios en el código HTML?', topic: 'html' },
    { text: '¿Cuál es la estructura básica de una página HTML? Menciona las tres etiquetas básicas.', topic: 'html' },
    { text: '¿Cuál es la función de la etiqueta <html>?', topic: 'html' },
    { text: '¿Qué etiqueta delimita la cabecera del documento y qué tipo de información contiene?', topic: 'html' },
    { text: '¿Qué etiqueta delimita el cuerpo del documento y qué contiene?', topic: 'html' },
    { text: '¿Qué contenido del <head> es visible para el usuario?', topic: 'html' },
    { text: '¿Cuál es la función de la etiqueta <title> y dónde se visualiza en el navegador?', topic: 'html' },
    { text: '¿Para qué se utilizan las etiquetas de encabezado (<h1> a <h6>)?', topic: 'html' },
    { text: '¿Cómo se clasifican jerárquicamente las etiquetas de encabezado?', topic: 'html' },
    { text: '¿Cuántos <h1> puede haber en un documento HTML?', topic: 'html' },
    { text: '¿Cuál es la función de la etiqueta <p>?', topic: 'html' },
    { text: '¿Cómo se genera un salto de línea dentro de un párrafo en HTML?', topic: 'html' },
    { text: '¿Qué etiqueta se utiliza para generar listas numeradas?', topic: 'html' },
    { text: '¿Qué etiqueta se utiliza para marcar cada ítem dentro de una lista (<ol> o <ul>)?', topic: 'html' },
    { text: 'Muestra un ejemplo de cómo se vería una lista numerada de dos ítems en el código HTML.', topic: 'html' },
    { text: '¿Qué etiqueta se utiliza para generar listas NO numeradas?', topic: 'html' },
    { text: '¿Cuál es la sintaxis básica para la etiqueta de imagen <img>?', topic: 'html' },
    { text: '¿Qué etiqueta se utiliza para crear vínculos (enlaces)?', topic: 'html' },
    { text: 'Menciona al menos tres lugares a los que se puede establecer un vínculo.', topic: 'html' },
    { text: '¿Para qué se utiliza la etiqueta <div>?', topic: 'html' },
    { text: '¿Qué etiqueta se utiliza para crear tablas?', topic: 'html' },
    { text: '¿Qué significa HTML5 DOCTYPE?', topic: 'html' },
    { text: '¿Cuál es la etiqueta semántica que se utiliza para la cabecera de un documento?', topic: 'html_semantico' },
    { text: '¿Cuál es la etiqueta semántica que se utiliza para la sección de navegación?', topic: 'html_semantico' },
    { text: '¿Qué etiqueta semántica delimita el contenido principal del documento?', topic: 'html_semantico' },
    { text: '¿Para qué se utiliza la etiqueta semántica <section>?', topic: 'html_semantico' },
    { text: '¿Cuál es el propósito de la etiqueta semántica <article>?', topic: 'html_semantico' },
    { text: '¿Qué etiqueta semántica se utiliza para contenido auxiliar o relacionado pero que no es parte del contenido principal?', topic: 'html_semantico' },
    { text: '¿Cuál es la etiqueta semántica para el pie de página?', topic: 'html_semantico' },
    { text: '¿Cuál es la diferencia entre una etiqueta de bloque y una de línea?', topic: 'html' },
    { text: '¿Qué propiedad CSS se utiliza para controlar el comportamiento de bloque/línea de un elemento?', topic: 'html' },
    { text: 'Menciona la sintaxis básica de la etiqueta <table> con sus componentes principales (<tr>, <th>, <td>).', topic: 'html' },
    { text: '¿Qué es un atributo y dónde se coloca en la sintaxis de una etiqueta HTML?', topic: 'html' },
    { text: 'Si una etiqueta se define como <h1 id="titulo">, ¿qué representa id y qué representa "titulo"?', topic: 'html' },
    { text: '¿Qué es el "Formateo de Texto" en HTML y menciona una etiqueta de formateo?', topic: 'html' },
    { text: '¿Cuál es el propósito del atributo href en la etiqueta <a>?', topic: 'html' },
    { text: 'Menciona las 6 etiquetas de encabezado que existen.', topic: 'html' },
    { text: '¿Qué pasa si colocas contenido fuera de la etiqueta <html>?', topic: 'html' },
    { text: '¿Cómo se diferencia la etiqueta <title> de las etiquetas de encabezado <h1> a <h6>?', topic: 'html' },
    { text: '¿Qué se necesita para vincular un archivo CSS externo al HTML?', topic: 'html' },

    // 3. CSS Básico y Modelo de Caja (40 Preguntas)
    { text: '¿Cuál es la sintaxis básica del código CSS?', topic: 'css_basico' },
    { text: 'En la sintaxis CSS, ¿qué representa el "selector"?', topic: 'css_basico' },
    { text: '¿Qué representa la "propiedad" en la sintaxis CSS?', topic: 'css_basico' },
    { text: '¿Cómo termina cada "declaración" en CSS?', topic: 'css_basico' },
    { text: 'Muestra un ejemplo de una regla CSS para cambiar el color de fuente de un <h1> a azul.', topic: 'css_basico' },
    { text: 'Menciona las tres formas de establecer un estilo CSS en un documento HTML.', topic: 'css_basico' },
    { text: '¿Cuál es la forma "menos recomendada" de vincular CSS con HTML?', topic: 'css_basico' },
    { text: '¿Dónde van las etiquetas <style> para CSS incrustado?', topic: 'css_basico' },
    { text: '¿Cuál es la forma "más recomendada" de vincular CSS con HTML y por qué?', topic: 'css_basico' },
    { text: '¿Qué etiqueta HTML se utiliza para vincular un archivo .css externo?', topic: 'css_basico' },
    { text: '¿Qué valor toma el atributo rel para las hojas de estilo en el vínculo externo?', topic: 'css_basico' },
    { text: '¿Qué indica el atributo href al vincular un archivo CSS?', topic: 'css_basico' },
    { text: '¿Qué es el Selector Universal en CSS y cómo se indica?', topic: 'css_basico' },
    { text: '¿Para qué se utiliza principalmente el Selector Universal?', topic: 'css_basico' },
    { text: '¿Qué selecciona el Selector de Etiqueta?', topic: 'css_basico' },
    { text: 'Muestra un ejemplo de un Selector de Etiqueta.', topic: 'css_basico' },
    { text: '¿Para qué sirve el Selector de Clase?', topic: 'css_basico' },
    { text: '¿Cómo se aplica un selector de clase a un elemento HTML?', topic: 'css_basico' },
    { text: '¿Cómo se indican los selectores de clase en el archivo CSS? Muestra un ejemplo.', topic: 'css_basico' },
    { text: '¿Puede repetirse un selector de clase en una misma página?', topic: 'css_basico' },
    { text: '¿Cuál es la principal diferencia entre el atributo id y el atributo class en HTML/CSS?', topic: 'css_basico' },
    { text: '¿Cómo se indica un selector de ID en el archivo CSS? Muestra un ejemplo.', topic: 'css_basico' },
    { text: 'Menciona la propiedad CSS para cambiar el color del texto.', topic: 'css_basico' },
    { text: '¿Cuáles son las tres formas de expresar valores de color en CSS según los apuntes?', topic: 'css_basico' },
    { text: '¿Qué representa la letra "A" en el color RGBA?', topic: 'css_basico' },
    { text: '¿En qué rango van los valores de la transparencia (A) en RGBA?', topic: 'css_basico' },
    { text: '¿Cuál es la propiedad CSS para cambiar el tipo de fuente?', topic: 'css_basico' },
    { text: 'Menciona dos ejemplos de familias de fuentes seguros.', topic: 'css_basico' },
    { text: '¿Cuál es la propiedad CSS para cambiar el tamaño de la letra?', topic: 'css_basico' },
    { text: 'Menciona tres medidas posibles para el tamaño de letra (font-size).', topic: 'css_basico' },
    { text: '¿Cuál es la propiedad CSS para el estilo de fuente (normal, cursiva, etc.)?', topic: 'css_basico' },
    { text: '¿Qué son las etiquetas de bloque y de línea?', topic: 'css_basico' },
    { text: '¿Qué propiedad CSS permite alterar el comportamiento de bloque/línea de un elemento?', topic: 'css_basico' },
    { text: '¿Para qué se utiliza display: flex;?', topic: 'css_basico' },
    { text: '¿Qué valores toma la propiedad font-style?', topic: 'css_basico' },
    { text: '¿Qué es el "Modelo de Caja" en CSS?', topic: 'css_modelo_caja' },
    { text: '¿Qué es un selector en CSS?', topic: 'css_basico' },
    { text: '¿Qué significa px en la propiedad font-size?', topic: 'css_basico' },
    { text: '¿Qué significa em en la propiedad font-size?', topic: 'css_basico' },
    { text: '¿Cuál es el propósito de margin: 0; padding: 0; con el selector universal *?', topic: 'css_basico' },

    // 4. CSS Avanzado y Flexbox (40 Preguntas)
    { text: '¿Para qué se utiliza la regla @font-face?', topic: 'css_avanzado' },
    { text: 'Menciona los cuatro formatos de fuente que se deben convertir para usar @font-face.', topic: 'css_avanzado' },
    { text: '¿Qué propiedades son obligatorias dentro de la función @font-face?', topic: 'css_avanzado' },
    { text: '¿Qué propiedad CSS permite agregar un borde redondeado a cualquier caja o imagen?', topic: 'css_avanzado' },
    { text: 'Si border-radius tiene un solo valor, ¿a qué afecta?', topic: 'css_avanzado' },
    { text: '¿Qué valor de border-radius se utiliza para crear un círculo?', topic: 'css_avanzado' },
    { text: '¿Qué propiedad permite aplicar una sombra a un texto?', topic: 'css_avanzado' },
    { text: '¿Cuántos valores posee la propiedad text-shadow y qué representan?', topic: 'css_avanzado' },
    { text: '¿Qué propiedad permite darle sombra a las cajas o imágenes?', topic: 'css_avanzado' },
    { text: '¿Qué palabra clave en box-shadow se utiliza para generar una sombra interna?', topic: 'css_avanzado' },
    { text: '¿Cuáles son las dos funciones para generar gradientes en CSS?', topic: 'css_avanzado' },
    { text: '¿A qué propiedades se puede aplicar la función linear-gradient?', topic: 'css_avanzado' },
    { text: '¿Qué función de gradiente puede incluir una "forma" en sus parámetros?', topic: 'css_avanzado' },
    { text: '¿Qué propiedad permite modificar la opacidad de una caja o elemento?', topic: 'css_avanzado' },
    { text: '¿En qué rango de valores decimales va la propiedad opacity?', topic: 'css_avanzado' },
    { text: '¿Cuál es el valor por defecto de opacity?', topic: 'css_avanzado' },
    { text: '¿Qué propiedad modifica la forma de un elemento?', topic: 'css_avanzado' },
    { text: 'Menciona las cuatro funciones básicas que utiliza la propiedad transform.', topic: 'css_avanzado' },
    { text: '¿Qué efecto tiene un valor negativo en la función scale?', topic: 'css_avanzado' },
    { text: '¿En qué unidad se expresa el parámetro de la función rotate?', topic: 'css_avanzado' },
    { text: '¿Cuántos valores recibe la función skew y qué representan?', topic: 'css_avanzado' },
    { text: '¿En qué unidad se expresa la función translate?', topic: 'css_avanzado' },
    { text: '¿Qué propiedad sirve para controlar la repetición de un fondo?', topic: 'css_avanzado' },
    { text: '¿Cuál es el valor por defecto de la propiedad background-repeat?', topic: 'css_avanzado' },
    { text: '¿Qué es Flexbox, según los apuntes?', topic: 'flexbox' },
    { text: '¿Qué elementos son necesarios para utilizar Flexbox?', topic: 'flexbox' },
    { text: '¿Qué propiedad se utiliza en el elemento contenedor para definir Flexbox?', topic: 'flexbox' },
    { text: '¿Qué establece la propiedad flex-direction en el contenedor?', topic: 'flexbox' },
    { text: 'Menciona los cuatro valores posibles de flex-direction.', topic: 'flexbox' },
    { text: '¿Qué valor de flex-direction ordena los elementos verticalmente de abajo arriba?', topic: 'flexbox' },
    { text: '¿Qué propiedad redistribuye los elementos para que entren en una o más líneas?', topic: 'flexbox' },
    { text: '¿Cuál es el valor por defecto de flex-wrap?', topic: 'flexbox' },
    { text: '¿Qué propiedad distribuye la posición de los elementos en el eje horizontal?', topic: 'flexbox' },
    { text: '¿Cuál es el valor por defecto de justify-content?', topic: 'flexbox' },
    { text: '¿Qué valor de justify-content centra horizontalmente los elementos?', topic: 'flexbox' },
    { text: '¿Qué propiedad distribuye la posición de los elementos en el eje vertical?', topic: 'flexbox' },
    { text: '¿Qué valor de align-items hace que los elementos hijos ocupen todo el ancho (o alto) del contenedor?', topic: 'flexbox' },
    { text: '¿Qué propiedad permite distribuir verticalmente los elementos cuando hay varias filas?', topic: 'flexbox' },
    { text: '¿Qué propiedad de item (hijo) permite cambiar su orden?', topic: 'flexbox' },
    { text: '¿Qué define la propiedad flex-grow?', topic: 'flexbox' },
    { text: '¿Cuál es el valor por defecto de flex-grow?', topic: 'flexbox' },
    { text: '¿Qué define la propiedad flex-basis?', topic: 'flexbox' },
    { text: '¿Qué propiedad permite alinear un elemento hijo en forma individual?', topic: 'flexbox' },
    { text: '¿Por qué se debe usar prefijos como -webkit- o -ms- en algunas propiedades de Flexbox?', topic: 'flexbox' },
    { text: 'Menciona un valor de justify-content que distribuya los elementos dejando el mismo espaciado entre ellos.', topic: 'flexbox' },
    { text: 'Menciona un valor de align-items que ubique los elementos desde el inicio del borde superior del contenedor.', topic: 'flexbox' },
    { text: '¿Cómo se expresa la función scale si se quieren escalar los ejes x e y por separado?', topic: 'css_avanzado' },
    { text: '¿Qué propiedad permite controlar el posicionamiento de un elemento (Static, Relative, Absolute, Fixed)?', topic: 'css_avanzado' },
    { text: '¿Cuál es el comportamiento de position: static?', topic: 'css_avanzado' },
    { text: '¿Para qué se utiliza la propiedad z-index?', topic: 'css_avanzado' },

    // 5. JavaScript (40 Preguntas)
    { text: '¿Qué tipo de lenguaje de programación es JavaScript?', topic: 'javascript' },
    { text: '¿En qué se utilizaba JavaScript inicialmente?', topic: 'javascript' },
    { text: '¿Qué herramienta popularizó el uso de JavaScript en ámbitos como servidores (backend)?', topic: 'javascript' },
    { text: '¿Qué es el "motor de javascript" en un navegador?', topic: 'javascript' },
    { text: '¿Cuál es el motor de JavaScript desarrollado por Google para el proyecto Chromium?', topic: 'javascript' },
    { text: 'Menciona al menos tres navegadores web cuyo código fuente está basado en Chromium y usan el motor V8.', topic: 'javascript' },
    { text: '¿Cuál es el motor de JavaScript del navegador Firefox?', topic: 'javascript' },
    { text: '¿Cuál es el motor de JavaScript del navegador Safari?', topic: 'javascript' },
    { text: '¿El código JavaScript que uno escribe varía dependiendo del navegador en el que se corra?', topic: 'javascript' },
    { text: '¿Qué organización se encarga de estandarizar el comportamiento de los lenguajes de scripting?', topic: 'javascript' },
    { text: '¿Qué es ECMAScript?', topic: 'javascript' },
    { text: '¿Qué herramienta provee el navegador para realizar pruebas sencillas y ejecutar código JavaScript?', topic: 'javascript' },
    { text: '¿Cómo se puede abrir la consola del navegador usando el teclado (en la mayoría de los casos)?', topic: 'javascript' },
    { text: '¿Qué función predeterminada de JavaScript muestra un popup con un texto? Muestra su sintaxis.', topic: 'javascript' },
    { text: '¿Qué es un "parámetro" en el contexto de una función de JavaScript?', topic: 'javascript' },
    { text: '¿Qué función de JavaScript muestra un cuadro de diálogo que le pide al usuario que ingrese texto?', topic: 'javascript' },
    { text: '¿Qué es una "variable" en programación?', topic: 'javascript' },
    { text: '¿Cuál es la principal función de las variables en JavaScript?', topic: 'javascript' },
    { text: 'Menciona las tres maneras de declarar una variable en JavaScript.', topic: 'javascript' },
    { text: '¿Cuál es la mejor opción para declarar una variable que NO cambiará de valor?', topic: 'javascript' },
    { text: '¿Cuál es la mejor opción para declarar una variable que SÍ cambiará de valor?', topic: 'javascript' },
    { text: '¿Qué define el alcance y el tiempo de vida de las variables en JavaScript?', topic: 'javascript' },
    { text: '¿Qué son los "bloques de código" en JavaScript?', topic: 'javascript' },
    { text: 'Menciona al menos 3 tipos de datos primitivos en JavaScript.', topic: 'javascript' },
    { text: 'Menciona un ejemplo de un operador aritmético.', topic: 'javascript' },
    { text: 'Menciona un ejemplo de un operador de asignación.', topic: 'javascript' },
    { text: 'Menciona un ejemplo de un operador de comparación.', topic: 'javascript' },
    { text: '¿Para qué se utilizan las estructuras condicionales en JavaScript?', topic: 'javascript' },
    { text: '¿Qué son las funciones en JavaScript?', topic: 'javascript' },
    { text: '¿Para qué se utilizan los métodos típicos para manipular cadenas (strings)?', topic: 'javascript' },
    { text: '¿Para qué se utilizan los métodos típicos para manipular arreglos (arrays)?', topic: 'javascript' },
    { text: '¿Qué significa DOM?', topic: 'javascript_dom' },
    { text: 'Menciona un método para acceder a un elemento del DOM buscando por su ID.', topic: 'javascript_dom' },
    { text: 'Menciona una forma de buscar elementos del DOM usando nombres de clases de CSS.', topic: 'javascript_dom' },
    { text: 'Menciona una forma de buscar elementos del DOM usando selectores de CSS.', topic: 'javascript_dom' },
    { text: '¿Qué se hace en JavaScript para responder a las interacciones del usuario (como un clic en un botón)?', topic: 'javascript_dom' },
    { text: '¿Por qué el valor de una función prompt() se puede almacenar en una variable?', topic: 'javascript' },
    { text: '¿Qué hace const con el valor de la variable que declara?', topic: 'javascript' },
    { text: '¿Qué le permite let a la variable que declara?', topic: 'javascript' },
    { text: '¿Qué se entiende por "ECMAScript 6+" o "ES6+" en el contexto de JavaScript?', topic: 'javascript' },

    // 6. Preguntas Avanzadas y Conceptuales (19 Preguntas)
    { text: 'Si quiero detectar cuando un botón X es clickeado, ¿qué método de JavaScript debo utilizar?', topic: 'javascript_dom' },
    { text: 'Si tengo la línea nodoButton.addEventListener(\'click\', miCallback), ¿qué tiene que suceder para que se ejecute la función miCallback que se pasa por parámetro?', topic: 'javascript_dom' },
    { text: 'Si quiero que el sitio web sea semántico, ¿qué etiquetas HTML debería utilizar en lugar de un <div> o un <span> genéricos para el encabezado, navegación y pie de página?', topic: 'html_semantico' },
    { text: 'Si quiero que al enviar un formulario se envíen correctamente los valores de los campos, ¿qué propiedad HTML no me debo olvidar de agregar a las etiquetas de entrada (<input>, <textarea>, <select>)?', topic: 'html' },
    { text: 'En el Modelo de Caja de CSS, si defino un width: 100px y luego agrego padding: 10px y border: 5px solid black, ¿cuál será el ancho total real del elemento por defecto?', topic: 'css_modelo_caja' },
    { text: 'Si quiero forzar a que el ancho de un elemento (width) incluya tanto el padding como el border en el cálculo total, ¿qué propiedad CSS debo utilizar y con qué valor?', topic: 'css_modelo_caja' },
    { text: '¿Cuál es la diferencia fundamental en el alcance (scope) entre las variables declaradas con var, let y const en JavaScript (especialmente en relación con los bloques de código)?', topic: 'javascript' },
    { text: 'En CSS, ¿qué sucede si un elemento tiene asignados estilos contradictorios (ej. color: red; y luego color: blue;) y cómo determina el navegador cuál aplicar?', topic: 'css_basico' },
    { text: 'Para evitar que un elemento sea afectado por otros estilos y garantizar que mi regla CSS se aplique siempre (sin usar IDs si puedo), ¿qué tengo que aumentar en mi selector?', topic: 'css_basico' },
    { text: 'Si estoy utilizando Flexbox en un contenedor y los ítems se desbordan de la línea, ¿qué propiedad debo usar para que los ítems se distribuyan en varias líneas?', topic: 'flexbox' },
    { text: 'En Flexbox, ¿qué propiedad debo modificar para centrar los elementos hijos del contenedor tanto horizontal como verticalmente? (Mencionar ambas propiedades y sus valores).', topic: 'flexbox' },
    { text: '¿Qué son los polyfills o shims en el contexto de la compatibilidad de navegadores con características modernas de CSS o JavaScript (como Flexbox o ES6+)?', topic: 'javascript' },
    { text: 'Si necesito que un fondo de imagen no se repita y se posicione en el centro superior del contenedor, ¿qué propiedades CSS debo usar y con qué valores?', topic: 'css_avanzado' },
    { text: '¿Cuál de las funciones de la propiedad transform de CSS me permite rotar un elemento y cuál me permite moverlo? ¿En qué unidades se expresan típicamente sus valores?', topic: 'css_avanzado' },
    { text: '¿Por qué la forma de vincular CSS "en línea" (atributo style) es considerada la "menos recomendada"?', topic: 'css_basico' },
    { text: 'Si un servidor web solo devuelve archivos en formato HTML como respuesta, ¿cómo se logra que el cliente vea estilos (CSS) e interactividad (JavaScript)?', topic: 'introduccion' },
    { text: 'En JavaScript, ¿cuál es el propósito del objeto window o globalThis y cómo se relaciona con el código que escribimos en el navegador?', topic: 'javascript' },
    { text: 'Si un elemento tiene position: absolute; y su elemento padre tiene position: static;, ¿a qué se referenciará la posición del elemento absoluto (ej. top: 10px)?', topic: 'css_avanzado' },
    { text: 'Cuando se utiliza linear-gradient para un fondo, ¿qué significa el valor to bottom?', topic: 'css_avanzado' },
];
