import { Problem } from '../database/schemas/problem.schema';

export const problemSeeds: Problem[] = [
    {
        title: 'Suma de tres números',
        description: 'Escribe una función solve(x, y, z) que retorne la suma de los tres números.',
        params: ['x', 'y', 'z'],
        testCases: [
            { input: [1, 2, 3], expected: 6, sample: true },
            { input: [-5, 10, 0], expected: 5, sample: true },
            { input: [100, -50, 25], expected: 75, sample: true },
            { input: [0, 0, 0], expected: 0, sample: false },
            { input: [-1, -2, -3], expected: -6, sample: false },
            { input: [7, 7, 7], expected: 21, sample: false },
            { input: [-100, 100, 50], expected: 50, sample: false },
            { input: [999, 1, 0], expected: 1000, sample: false },
            { input: [-25, -25, 50], expected: 0, sample: false },
            { input: [12, 34, 56], expected: 102, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: '¿Es par?',
        description: 'Escribe una función solve(n) que retorne true si n es par, false si es impar.',
        params: ['n'],
        testCases: [
            { input: [4], expected: true, sample: true },
            { input: [7], expected: false, sample: true },
            { input: [0], expected: true, sample: true },
            { input: [-2], expected: true, sample: false },
            { input: [-3], expected: false, sample: false },
            { input: [100], expected: true, sample: false },
            { input: [99], expected: false, sample: false },
            { input: [1], expected: false, sample: false },
            { input: [2024], expected: true, sample: false },
            { input: [12345], expected: false, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Suma de un arreglo',
        description: 'Escribe una función solve(nums) que reciba un arreglo de números y retorne la suma de todos sus elementos. El arreglo vacío suma 0.',
        params: ['nums'],
        testCases: [
            { input: [[1, 2, 3]], expected: 6, sample: true },
            { input: [[10, -5, 2, 1]], expected: 8, sample: true },
            { input: [[]], expected: 0, sample: true },
            { input: [[100]], expected: 100, sample: false },
            { input: [[-1, -2, -3]], expected: -6, sample: false },
            { input: [[5, 5, 5, 5]], expected: 20, sample: false },
            { input: [[1000, -1000, 7]], expected: 7, sample: false },
            { input: [[2, 4, 6, 8, 10]], expected: 30, sample: false },
            { input: [[0, 0, 0, 1]], expected: 1, sample: false },
            { input: [[50, -20, 30, -60]], expected: 0, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'El mayor de un arreglo',
        description: 'Escribe una función solve(nums) que reciba un arreglo de números no vacío y retorne el mayor de todos ellos.',
        params: ['nums'],
        testCases: [
            { input: [[3, 7, 2]], expected: 7, sample: true },
            { input: [[10, 10, 1]], expected: 10, sample: true },
            { input: [[-5, -2, -9]], expected: -2, sample: true },
            { input: [[1]], expected: 1, sample: false },
            { input: [[0, 3, 8, 2]], expected: 8, sample: false },
            { input: [[100, -100, 50]], expected: 100, sample: false },
            { input: [[4, 4, 4]], expected: 4, sample: false },
            { input: [[-1, -3, -2]], expected: -1, sample: false },
            { input: [[9, 1, 8, 2, 7]], expected: 9, sample: false },
            { input: [[13, 13, 1]], expected: 13, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Elementos no numéricos',
        description: 'Escribe una función solve(arr) que reciba un arreglo con elementos de cualquier tipo y retorne la cantidad de elementos que NO son de tipo número (ayuda: usa typeof).',
        params: ['arr'],
        testCases: [
            { input: [['a', 1, 'b']], expected: 2, sample: true },
            { input: [[1, 2, 3]], expected: 0, sample: true },
            { input: [['x', true, null]], expected: 3, sample: true },
            { input: [[1, '2', 3]], expected: 1, sample: false },
            { input: [[]], expected: 0, sample: false },
            { input: [[true, false, 5]], expected: 2, sample: false },
            { input: [[null, undefined, 0]], expected: 2, sample: false },
            { input: [['hola']], expected: 1, sample: false },
            { input: [[{}, [], 7]], expected: 2, sample: false },
            { input: [[1, 2, 'tres', 4, 'cinco', 6]], expected: 2, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Contar pares en un arreglo',
        description: 'Escribe una función solve(nums) que reciba un arreglo de números enteros y retorne cuántos de ellos son pares.',
        params: ['nums'],
        testCases: [
            { input: [[1, 2, 3, 4]], expected: 2, sample: true },
            { input: [[2, 4, 6]], expected: 3, sample: true },
            { input: [[1, 3, 5]], expected: 0, sample: true },
            { input: [[]], expected: 0, sample: false },
            { input: [[0]], expected: 1, sample: false },
            { input: [[-2, -4, 5]], expected: 2, sample: false },
            { input: [[7]], expected: 0, sample: false },
            { input: [[10, 11, 12, 13, 14]], expected: 3, sample: false },
            { input: [[100, 101]], expected: 1, sample: false },
            { input: [[0, 1, 2, 3, 4, 5]], expected: 3, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Sumar solo los positivos',
        description: 'Escribe una función solve(nums) que reciba un arreglo de números y retorne la suma únicamente de los positivos (los ceros y negativos se ignoran).',
        params: ['nums'],
        testCases: [
            { input: [[1, -2, 3]], expected: 4, sample: true },
            { input: [[-1, -2, -3]], expected: 0, sample: true },
            { input: [[5, 5, -5]], expected: 10, sample: true },
            { input: [[]], expected: 0, sample: false },
            { input: [[0, -1, 2]], expected: 2, sample: false },
            { input: [[10, -10]], expected: 10, sample: false },
            { input: [[-7]], expected: 0, sample: false },
            { input: [[1, 2, 3, 4]], expected: 10, sample: false },
            { input: [[0, 0, 0]], expected: 0, sample: false },
            { input: [[50, -25, 25, -50]], expected: 75, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Texto invertido',
        description: "Escribe una función solve(texto) que reciba un texto y lo retorne invertido. Por ejemplo, 'hola' se convierte en 'aloh'.",
        params: ['texto'],
        testCases: [
            { input: ['hola'], expected: 'aloh', sample: true },
            { input: ['abc'], expected: 'cba', sample: true },
            { input: ['a'], expected: 'a', sample: true },
            { input: [''], expected: '', sample: false },
            { input: ['javascript'], expected: 'tpircsavaj', sample: false },
            { input: ['ab'], expected: 'ba', sample: false },
            { input: ['oso'], expected: 'oso', sample: false },
            { input: ['12345'], expected: '54321', sample: false },
            { input: ['Universidad'], expected: 'dadisrevinU', sample: false },
            { input: ['anita'], expected: 'atina', sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Contar vocales',
        description: 'Escribe una función solve(texto) que reciba un texto en minúsculas y retorne cuántas vocales (a, e, i, o, u) contiene.',
        params: ['texto'],
        testCases: [
            { input: ['hola'], expected: 2, sample: true },
            { input: ['javascript'], expected: 3, sample: true },
            { input: ['xyz'], expected: 0, sample: true },
            { input: [''], expected: 0, sample: false },
            { input: ['universidad'], expected: 5, sample: false },
            { input: ['bcdfg'], expected: 0, sample: false },
            { input: ['programacion'], expected: 5, sample: false },
            { input: ['aeiou'], expected: 5, sample: false },
            { input: ['murcielago'], expected: 5, sample: false },
            { input: ['hola mundo'], expected: 4, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: '¿Es palíndromo?',
        description: "Escribe una función solve(texto) que retorne true si el texto se lee igual al derecho y al revés (todo en minúsculas, sin espacios). Por ejemplo, 'oso' es palíndromo.",
        params: ['texto'],
        testCases: [
            { input: ['oso'], expected: true, sample: true },
            { input: ['casa'], expected: false, sample: true },
            { input: ['reconocer'], expected: true, sample: true },
            { input: [''], expected: true, sample: false },
            { input: ['a'], expected: true, sample: false },
            { input: ['radar'], expected: true, sample: false },
            { input: ['hola'], expected: false, sample: false },
            { input: ['neuquen'], expected: true, sample: false },
            { input: ['perro'], expected: false, sample: false },
            { input: ['sometemos'], expected: true, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Segundo mayor del arreglo',
        description: 'Escribe una función solve(nums) que reciba un arreglo de números con al menos dos valores distintos y retorne el segundo mayor.',
        params: ['nums'],
        testCases: [
            { input: [[1, 5, 3]], expected: 3, sample: true },
            { input: [[10, 2, 8]], expected: 8, sample: true },
            { input: [[7, 3]], expected: 3, sample: true },
            { input: [[2, 9]], expected: 2, sample: false },
            { input: [[1, 2, 3, 4, 5]], expected: 4, sample: false },
            { input: [[-1, -5, -3]], expected: -3, sample: false },
            { input: [[100, 1, 50, 25]], expected: 50, sample: false },
            { input: [[0, -1, 1]], expected: 0, sample: false },
            { input: [[7, 14, 21, 35]], expected: 21, sample: false },
            { input: [[6, 2, 8, 4]], expected: 6, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Filtrar mayores que n',
        description: 'Escribe una función solve(nums, n) que reciba un arreglo de números y un número n, y retorne un arreglo con los elementos estrictamente mayores que n, en el mismo orden.',
        params: ['nums', 'n'],
        testCases: [
            { input: [[1, 5, 8], 4], expected: [5, 8], sample: true },
            { input: [[10, 2, 30], 5], expected: [10, 30], sample: true },
            { input: [[1, 2], 10], expected: [], sample: true },
            { input: [[], 0], expected: [], sample: false },
            { input: [[5, 5, 5], 4], expected: [5, 5, 5], sample: false },
            { input: [[-3, 0, 3], -1], expected: [0, 3], sample: false },
            { input: [[1, 2, 3], 2], expected: [3], sample: false },
            { input: [[100], 99], expected: [100], sample: false },
            { input: [[0, 0, 1], 0], expected: [1], sample: false },
            { input: [[7, 3, 9, 1, 8], 5], expected: [7, 9, 8], sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Suma de dígitos',
        description: 'Escribe una función solve(n) que reciba un número entero no negativo y retorne la suma de sus dígitos. Por ejemplo, 123 da 1 + 2 + 3 = 6.',
        params: ['n'],
        testCases: [
            { input: [123], expected: 6, sample: true },
            { input: [45], expected: 9, sample: true },
            { input: [7], expected: 7, sample: true },
            { input: [0], expected: 0, sample: false },
            { input: [100], expected: 1, sample: false },
            { input: [9999], expected: 36, sample: false },
            { input: [5000], expected: 5, sample: false },
            { input: [12], expected: 3, sample: false },
            { input: [111111], expected: 6, sample: false },
            { input: [98765], expected: 35, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: '¿Es primo?',
        description: 'Escribe una función solve(n) que retorne true si n es un número primo, false en caso contrario. Recuerda que los números menores que 2 no son primos.',
        params: ['n'],
        testCases: [
            { input: [7], expected: true, sample: true },
            { input: [10], expected: false, sample: true },
            { input: [2], expected: true, sample: true },
            { input: [0], expected: false, sample: false },
            { input: [1], expected: false, sample: false },
            { input: [17], expected: true, sample: false },
            { input: [-3], expected: false, sample: false },
            { input: [25], expected: false, sample: false },
            { input: [97], expected: true, sample: false },
            { input: [49], expected: false, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Factorial',
        description: 'Escribe una función solve(n) que calcule el factorial de n. El factorial de 0 es 1 y el de n es n multiplicado por el factorial de n-1.',
        params: ['n'],
        testCases: [
            { input: [0], expected: 1, sample: true },
            { input: [5], expected: 120, sample: true },
            { input: [3], expected: 6, sample: true },
            { input: [1], expected: 1, sample: false },
            { input: [10], expected: 3628800, sample: false },
            { input: [7], expected: 5040, sample: false },
            { input: [2], expected: 2, sample: false },
            { input: [12], expected: 479001600, sample: false },
            { input: [4], expected: 24, sample: false },
            { input: [8], expected: 40320, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Obtener propiedad de un objeto',
        description: 'Escribe una función solve(obj, clave) que reciba un objeto y el nombre de una propiedad, y retorne el valor de esa propiedad. La propiedad siempre existe en el objeto.',
        params: ['obj', 'clave'],
        testCases: [
            { input: [{ nombre: 'Ana' }, 'nombre'], expected: 'Ana', sample: true },
            { input: [{ curso: 'JS', anio: 2026 }, 'anio'], expected: 2026, sample: true },
            { input: [{ activo: true }, 'activo'], expected: true, sample: true },
            { input: [{ ciudad: 'LP', pais: 'BO' }, 'pais'], expected: 'BO', sample: false },
            { input: [{ nota1: 90, nota2: 70 }, 'nota1'], expected: 90, sample: false },
            { input: [{ x: { y: 1 } }, 'x'], expected: { y: 1 }, sample: false },
            { input: [{ id: 7 }, 'id'], expected: 7, sample: false },
            { input: [{ saludo: 'hola' }, 'saludo'], expected: 'hola', sample: false },
            { input: [{ vacio: null }, 'vacio'], expected: null, sample: false },
            { input: [{ lista: [1, 2] }, 'lista'], expected: [1, 2], sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Suma de edades',
        description: 'Escribe una función solve(personas) que reciba un arreglo de objetos con la forma { nombre, edad } y retorne la suma de todas las edades.',
        params: ['personas'],
        testCases: [
            { input: [[{ nombre: 'Ana', edad: 10 }, { nombre: 'Luis', edad: 20 }]], expected: 30, sample: true },
            { input: [[{ nombre: 'Bea', edad: 18 }]], expected: 18, sample: true },
            { input: [[]], expected: 0, sample: true },
            { input: [[{ nombre: 'A', edad: 5 }, { nombre: 'B', edad: 5 }, { nombre: 'C', edad: 5 }]], expected: 15, sample: false },
            { input: [[{ nombre: 'X', edad: 0 }, { nombre: 'Y', edad: 40 }]], expected: 40, sample: false },
            { input: [[{ nombre: 'Z', edad: 33 }, { nombre: 'W', edad: 33 }]], expected: 66, sample: false },
            { input: [[{ nombre: 'N', edad: 1 }, { nombre: 'M', edad: 2 }, { nombre: 'O', edad: 3 }, { nombre: 'P', edad: 4 }]], expected: 10, sample: false },
            { input: [[{ nombre: 'Anciano', edad: 99 }]], expected: 99, sample: false },
            { input: [[{ nombre: 'J', edad: 17 }, { nombre: 'K', edad: 18 }]], expected: 35, sample: false },
            { input: [[{ nombre: 'Q', edad: 25 }, { nombre: 'R', edad: 25 }, { nombre: 'S', edad: 0 }]], expected: 50, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Total del carrito',
        description: 'Escribe una función solve(items) que reciba un arreglo de productos con la forma { producto, precio, cantidad } y retorne el total a pagar (suma de precio * cantidad de cada item).',
        params: ['items'],
        testCases: [
            { input: [[{ producto: 'pan', precio: 2, cantidad: 3 }]], expected: 6, sample: true },
            { input: [[{ producto: 'leche', precio: 5, cantidad: 2 }, { producto: 'pan', precio: 2, cantidad: 3 }]], expected: 16, sample: true },
            { input: [[]], expected: 0, sample: true },
            { input: [[{ producto: 'lapiz', precio: 1, cantidad: 0 }]], expected: 0, sample: false },
            { input: [[{ producto: 'a', precio: 10, cantidad: 10 }]], expected: 100, sample: false },
            { input: [[{ producto: 'b', precio: 3, cantidad: 4 }, { producto: 'c', precio: 7, cantidad: 2 }]], expected: 26, sample: false },
            { input: [[{ producto: 'd', precio: 1, cantidad: 1 }, { producto: 'e', precio: 1, cantidad: 1 }, { producto: 'f', precio: 1, cantidad: 1 }]], expected: 3, sample: false },
            { input: [[{ producto: 'g', precio: 50, cantidad: 2 }, { producto: 'h', precio: 25, cantidad: 4 }]], expected: 200, sample: false },
            { input: [[{ producto: 'i', precio: 999, cantidad: 1 }, { producto: 'j', precio: 1, cantidad: 999 }]], expected: 1998, sample: false },
            { input: [[{ producto: 'k', precio: 4, cantidad: 5 }, { producto: 'l', precio: 6, cantidad: 5 }, { producto: 'm', precio: 0, cantidad: 100 }]], expected: 50, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'Promedio de notas',
        description: 'Escribe una función solve(estudiante) que reciba un objeto con la forma { nombre, notas } donde notas es un arreglo de números no vacío, y retorne el promedio de las notas.',
        params: ['estudiante'],
        testCases: [
            { input: [{ nombre: 'Ana', notas: [10, 8] }], expected: 9, sample: true },
            { input: [{ nombre: 'Luis', notas: [6, 6, 6] }], expected: 6, sample: true },
            { input: [{ nombre: 'Bea', notas: [10] }], expected: 10, sample: true },
            { input: [{ nombre: 'Calo', notas: [2, 3] }], expected: 2.5, sample: false },
            { input: [{ nombre: 'Dana', notas: [0, 10] }], expected: 5, sample: false },
            { input: [{ nombre: 'Elio', notas: [7, 7, 7, 7] }], expected: 7, sample: false },
            { input: [{ nombre: 'Fito', notas: [1, 1, 4, 2] }], expected: 2, sample: false },
            { input: [{ nombre: 'Gaby', notas: [5, 10, 15, 10] }], expected: 10, sample: false },
            { input: [{ nombre: 'Hugo', notas: [4, 6] }], expected: 5, sample: false },
            { input: [{ nombre: 'Ivo', notas: [9, 9, 9, 9, 9] }], expected: 9, sample: false },
        ],
        active: true,
    } as Problem,
    {
        title: 'La clave más valiosa',
        description: 'Escribe una función solve(obj) que reciba un objeto cuyos valores son números y retorne el nombre de la clave con el mayor valor. Si hay empate, retorna la primera clave que aparece con ese valor.',
        params: ['obj'],
        testCases: [
            { input: [{ a: 1, b: 5 }], expected: 'b', sample: true },
            { input: [{ oro: 100, plata: 50 }], expected: 'oro', sample: true },
            { input: [{ x: 3, y: 3, z: 1 }], expected: 'x', sample: true },
            { input: [{ uno: 1, dos: 2, tres: 3 }], expected: 'tres', sample: false },
            { input: [{ a: -5, b: -2 }], expected: 'b', sample: false },
            { input: [{ sol: 0, luna: 10 }], expected: 'luna', sample: false },
            { input: [{ m: 9 }], expected: 'm', sample: false },
            { input: [{ p: 4, q: 4, r: 2 }], expected: 'p', sample: false },
            { input: [{ juan: 80, ana: 95, eva: 90 }], expected: 'ana', sample: false },
            { input: [{ cero: 0 }], expected: 'cero', sample: false },
        ],
        active: true,
    } as Problem,
];
